---
title: "Demographic Tables"
editor: visual
html-table-processing: none
---

```{r}
library(tidyverse)
library(gt)
```

```{r}

# the combined data we put in the model
exp_data_full <- read.csv("../data/diary24_combined/created_data/exp_fmly_data.csv")



nrow(exp_data_full)

update_data_for_model <- function(lcm_data){

  lcm_data$FoodAlc = lcm_data$Food.Related + lcm_data$Alcohol
  lcm_data$Leisure = lcm_data$Recreational.Related + lcm_data$At..Home.Entertainment
  lcm_data$School = lcm_data$School.Supplies + lcm_data$Education
  lcm_data$Mandatory = lcm_data$Family.Spending + lcm_data$Hygiene + lcm_data$Medical + lcm_data$Clothing.Related
  lcm_data$Housing = lcm_data$House.Related
  lcm_data$Bike.or.Scooter.Travel = lcm_data$Bike.or.Scooter.or.other.Single.Rider.Travel
  lcm_data$Transpo = (lcm_data$Car.Fuel + lcm_data$Car.Maintenance + lcm_data$Taxi.or.Limo.Travel
                      + lcm_data$Bus.Travel + lcm_data$Train.Travel +lcm_data$Air.Travel + lcm_data$Bike.or.Scooter.Travel)

  quantile(lcm_data$Leisure)
  quantile(lcm_data$FoodAlc)
  quantile(lcm_data$School)
  quantile(lcm_data$Mandatory)
  quantile(lcm_data$Housing)

  quantile(lcm_data$Car.Fuel)
  quantile(lcm_data$Car.Maintenance)


  #Yes Categories
  lcm_data$FoodAlc = lcm_data$Food.Related + lcm_data$Alcohol
  lcm_data$Leisure = lcm_data$Recreational.Related + lcm_data$At..Home.Entertainment
  lcm_data$School = lcm_data$School.Supplies + lcm_data$Education
  lcm_data$Mandatory = lcm_data$Family.Spending + lcm_data$Hygiene + lcm_data$Medical + lcm_data$Clothing.Related
  lcm_data$Housing = lcm_data$House.Related
  lcm_data$Bike.or.Scooter.Travel = lcm_data$Bike.or.Scooter.or.other.Single.Rider.Travel
  lcm_data$Transpo = (lcm_data$Car.Fuel + lcm_data$Car.Maintenance + lcm_data$Taxi.or.Limo.Travel
                      + lcm_data$Bus.Travel + lcm_data$Train.Travel +lcm_data$Air.Travel + lcm_data$Bike.or.Scooter.Travel)
  
  quantile(lcm_data$Leisure)
  quantile(lcm_data$FoodAlc)
  quantile(lcm_data$School)
  quantile(lcm_data$Mandatory)
  quantile(lcm_data$Housing)
  
  quantile(lcm_data$Car.Fuel)
  quantile(lcm_data$Car.Maintenance)
  
  
  #Yes Categories
  lcm_data$LeiY = as.integer(factor(ifelse(lcm_data$Leisure>0,1,0)))
  lcm_data$FoodY = as.integer(factor(ifelse(lcm_data$FoodAlc>0,1,0)))
  lcm_data$SchoolY = as.integer(factor(ifelse(lcm_data$School>0,1,0)))
  lcm_data$ManY = as.integer(factor(ifelse(lcm_data$Mandatory>0,1,0)))
  lcm_data$HouseY = as.integer(factor(ifelse(lcm_data$Housing>0,1,0)))
  lcm_data$TranspoY = as.integer(factor(ifelse(lcm_data$Transpo>0,1,0)))
  #lcm_data$carY = as.integer(factor(ifelse(lcm_data$Car.Travel>0,1,0)))
  lcm_data$cargasY = as.integer(factor(ifelse(lcm_data$Car.Fuel>0,1,0)))
  lcm_data$carmaintY = as.integer(factor(ifelse(lcm_data$Car.Maintenance>0,1,0)))
  # lcm_data$carotherY = as.integer(factor(ifelse(lcm_data$Car.Other>0,1,0)))
  lcm_data$taxiY = as.integer(factor(ifelse(lcm_data$Taxi.or.Limo.Travel>0,1,0)))
  lcm_data$busY = as.integer(factor(ifelse(lcm_data$Bus.Travel>0,1,0)))
  lcm_data$trainY = as.integer(factor(ifelse(lcm_data$Train.Travel>0,1,0)))
  lcm_data$airY = as.integer(factor(ifelse(lcm_data$Air.Travel>0,1,0)))
  lcm_data$microY = as.integer(factor(ifelse(lcm_data$Bike.or.Scooter.Travel>0,1,0)))
  # sjmisc::frq(x=lcm_data[c("microY")], out="viewer")
  
  lcm_data$sum = lcm_data$LeiY +lcm_data$SchoolY + lcm_data$ManY + lcm_data$HouseY - 4
  # sjmisc::frq(x=lcm_data[c("sum")], out="viewer")
  
  #### cuts for non transpo ####
  cutslei <- c(-Inf, 0, 100, Inf)
  labslei <- c("Zero", "HundredB", "HighHunB")
  lcm_data$Lei_cat <- cut(lcm_data$Leisure,
                          breaks = cutslei,
                          labels = labslei,
                          right = TRUE,
                          ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("Lei_cat")], out="viewer")
  lcm_data$Lei_cat1 = as.integer(lcm_data$Lei_cat)
  
  cutsfood <- c(-Inf, 100, 500, Inf)
  labsfood <- c("OneHudB", "FiveHundredB", "HighFiveHunB")
  lcm_data$Food_cat <- cut(lcm_data$FoodAlc,
                           breaks = cutsfood,
                           labels = labsfood,
                           right = TRUE,
                           ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("Food_cat")], out="viewer")
  lcm_data$Food_cat1 = as.integer(lcm_data$Food_cat)
  
  cutsman <- c(-Inf, 0, 200, 500, Inf)
  labsman <- c("Zero", "two", "five", "over")
  lcm_data$Man_cat <- cut(lcm_data$Mandatory,
                          breaks = cutsman,
                          labels = labsman,
                          right = TRUE,
                          ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("Man_cat")], out="viewer")
  lcm_data$Man_cat1 = as.integer(lcm_data$Man_cat)
  
  cutshous <- c(-Inf, 0, 200, 500, Inf)
  labshous <- c("Zero", "two", "five", "over")
  lcm_data$House_cat <- cut(lcm_data$Housing,
                            breaks = cutshous,
                            labels = labshous,
                            right = TRUE,
                            ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("House_cat")], out="viewer")
  lcm_data$House_cat1 = as.integer(lcm_data$House_cat)
  
  
  #### cuts for transpo ####
  cutsC1 <- c(-Inf, 0, 50, 100, Inf)
  labsC1 <- c("Zero", "FiftyB", "HundredB", "HighHunB")
  
  cutsC2 <- c(-Inf, 0, 100, Inf)
  labsC2 <- c("Zero", "HundredB", "HighHunB")
  
  cutsC3 <- c(-Inf, 0, 100, Inf)
  labsC3 <- c("Zero", "HundredB", "HighHunB")
  
  cutsT <- c(-Inf, 0, 20, 50, Inf)
  labsT <- c("Zero", "TwentyB", "TwentyFifty", "HighFifB")
  
  cutsB <- c(-Inf, 0, Inf)
  labsB <- c("Zero", "Any")
  
  cutsTR <- c(-Inf, 0, 20, Inf)
  labsTR <- c("Zero", "TwentyB", "HighTwB")
  
  cutsA <- c(-Inf, 0, 500, Inf)
  labsA <- c("Zero", "FiveHB","HighFive")
  
  cutsM <- c(-Inf, 0, Inf)
  labsM <- c("Zero", "Any")
  
  lcm_data$carFuelP_cat
  lcm_data$carMainP_cat
  lcm_data$taxiP_cat
  lcm_data$busP_cat
  lcm_data$trainP_cat
  lcm_data$airP_cat
  lcm_data$microP_cat
  
  
  lcm_data$carFuelP_cat <- cut(lcm_data$Car.Fuel,
                               breaks = cutsC1,
                               labels = labsC1,
                               right = TRUE,
                               ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("carFuelP_cat")], out="viewer")
  lcm_data$carMainP_cat <- cut(lcm_data$Car.Maintenance,
                               breaks = cutsC2,
                               labels = labsC2,
                               right = TRUE,
                               ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("carMainP_cat")], out="viewer")
  # lcm_data$carOthP_cat <- cut(lcm_data$Car.Other,
  #                          breaks = cutsC3,
  #                          labels = labsC3,
  #                          right = TRUE,
  #                          ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("carOthP_cat")], out="viewer")
  lcm_data$taxiP_cat <- cut(lcm_data$Taxi.or.Limo.Travel,
                            breaks = cutsT,
                            labels = labsT,
                            right = TRUE,
                            ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("taxiP_cat")], out="viewer")
  lcm_data$busP_cat <- cut(lcm_data$Bus.Travel,
                           breaks = cutsB,
                           labels = labsB,
                           right = TRUE,
                           ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("busP_cat")], out="viewer")
  lcm_data$trainP_cat <- cut(lcm_data$Train.Travel,
                             breaks = cutsTR,
                             labels = labsTR,
                             right = TRUE,
                             ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("trainP_cat")], out="viewer")
  lcm_data$airP_cat <- cut(lcm_data$Air.Travel,
                           breaks = cutsA,
                           labels = labsA,
                           right = TRUE,
                           ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("airP_cat")], out="viewer")
  lcm_data$microP_cat <- cut(lcm_data$Bike.or.Scooter.Travel,
                             breaks = cutsM,
                             labels = labsM,
                             right = TRUE,
                             ordered_result = TRUE)
  # sjmisc::frq(x=lcm_data[c("microP_cat")], out="viewer")
  
  lcm_data$carFuelP_cat1 = as.numeric(lcm_data$carFuelP_cat)
  lcm_data$carMainP_cat1 = as.numeric(lcm_data$carMainP_cat)
  # lcm_data$carOthP_cat1 = as.integer(lcm_data$carOthP_cat)
  lcm_data$taxiP_cat1 = as.integer(lcm_data$taxiP_cat)
  lcm_data$busP_cat1 = as.integer(lcm_data$busP_cat)
  lcm_data$trainP_cat1 = as.integer(lcm_data$trainP_cat)
  lcm_data$airP_cat1 = as.integer(lcm_data$airP_cat)
  lcm_data$microP_cat1 = as.integer(lcm_data$microP_cat)
  
  # sjmisc::frq(x=lcm_data[c("carFuelP_cat1")], out="viewer")
  # sjmisc::frq(x=lcm_data[c("carMainP_cat1")], out="viewer")
  
  


  #demogrpahic changes
  lcm_data$veh3more = lcm_data$veh_3 + lcm_data$veh_more_3
  lcm_data$one_or_more_over_64 = lcm_data$one_pers_more_64_yd +
    lcm_data$two_pers_more_64_yd +
    lcm_data$more_two_pers_more_64_yd
  lcm_data$children_in_hh <- lcm_data$children_1 + lcm_data$children_2 + lcm_data$children_3plus
  lcm_data$spouse_in_hh <- lcm_data$married
  lcm_data$no_spouse_in_hh <- lcm_data$widowed + lcm_data$divorced + lcm_data$separated +lcm_data$never_married
  lcm_data$married_inc_under_50k <- ifelse(lcm_data$married + lcm_data$income_less_50k == 2, 1, 0)
  lcm_data$married_inc_over_50k <- ifelse(lcm_data$married
                                          + lcm_data$income_50k_to_75k
                                          + lcm_data$income_75k_to_100k
                                          + lcm_data$income_100k_to_200k
                                          + lcm_data$income_more_200k == 2,
                                          1, 0)
  lcm_data$children_and_under_50k <- ifelse(lcm_data$children_in_hh + lcm_data$income_less_50k == 2, 1, 0)
  lcm_data$children_and_over_50k <- ifelse(lcm_data$children_in_hh
                                           + lcm_data$income_50k_to_75k
                                           + lcm_data$income_75k_to_100k
                                           + lcm_data$income_100k_to_200k
                                           + lcm_data$income_more_200k == 2,
                                           1, 0)
  lcm_data$college <- lcm_data$edu_assoc_degree + lcm_data$edu_bachelors + lcm_data$edu_masters_doctorate
  lcm_data$no_college <- lcm_data$edu_elem + lcm_data$edu_high_school + lcm_data$edu_none + lcm_data$edu_some_college + lcm_data$edu_some_high_school
  lcm_data$less_bachelors <- lcm_data$edu_elem + lcm_data$edu_high_school + lcm_data$edu_none + lcm_data$edu_some_college + lcm_data$edu_some_high_school + lcm_data$edu_assoc_degree
  lcm_data$college_less_50k <- ifelse(lcm_data$college + lcm_data$income_less_50k == 2, 1, 0)
  lcm_data$college_more_50k <- ifelse(lcm_data$college
                                      + lcm_data$income_50k_to_75k
                                      + lcm_data$income_75k_to_100k
                                      + lcm_data$income_100k_to_200k
                                      + lcm_data$income_more_200k == 2,
                                      1, 0)
  lcm_data$no_college_less_50k <- ifelse(lcm_data$no_college + lcm_data$income_less_50k == 2, 1, 0)
  lcm_data$fam_single_parent <- lcm_data$fam_single_dad + lcm_data$fam_single_mom
  lcm_data$married_college <- lcm_data$married + lcm_data$college
  lcm_data$married_no_college <- lcm_data$married + lcm_data$no_college
  lcm_data$single_college <- lcm_data$no_spouse_in_hh + lcm_data$college
  lcm_data$single_no_college <- lcm_data$no_spouse_in_hh + lcm_data$no_college
  
  lcm_data$single_no_kids <- ifelse(lcm_data$no_spouse_in_hh + lcm_data$children_none == 2, 1, 0)
  lcm_data$single_kids <- ifelse(lcm_data$no_spouse_in_hh + lcm_data$children_in_hh == 2, 1, 0)
  lcm_data$married_no_kids <- ifelse(lcm_data$married + lcm_data$children_none == 2, 1, 0)
  lcm_data$married_kids <- ifelse(lcm_data$married + lcm_data$children_in_hh == 2, 1, 0)
  
  lcm_data$single_no_kids_no_65 <- ifelse(lcm_data$single_no_kids + lcm_data$no_pers_more_64_yd == 2, 1, 0)
  lcm_data$single_kids_no_65 <- ifelse(lcm_data$single_kids + lcm_data$no_pers_more_64_yd == 2, 1, 0)
  lcm_data$married_no_kids_no_65 <- ifelse(lcm_data$married_no_kids + lcm_data$no_pers_more_64_yd == 2, 1, 0)
  lcm_data$married_kids_no_65 <- ifelse(lcm_data$married_kids + lcm_data$no_pers_more_64_yd == 2, 1, 0)
  lcm_data$single_no_kids_65 <- ifelse(lcm_data$single_no_kids + lcm_data$one_or_more_over_64 == 2, 1, 0)
  lcm_data$single_kids_65 <- ifelse(lcm_data$single_kids + lcm_data$one_or_more_over_64 == 2, 1, 0)
  lcm_data$married_no_kids_65 <- ifelse(lcm_data$married_no_kids + lcm_data$one_or_more_over_64 == 2, 1, 0)
  lcm_data$married_kids_65 <- ifelse(lcm_data$married_kids + lcm_data$one_or_more_over_64 == 2, 1, 0)
  
  lcm_data$urban <- 1 - lcm_data$in_rural
  
  lcm_data$urban_northeast <- ifelse(lcm_data$urban + lcm_data$region_northeast == 2, 1, 0)
  lcm_data$urban_midwest <- ifelse(lcm_data$urban + lcm_data$region_midwest == 2, 1, 0)
  lcm_data$urban_south <- ifelse(lcm_data$urban + lcm_data$region_south == 2, 1, 0)
  lcm_data$urban_wes <- ifelse(lcm_data$urban + lcm_data$region_wes == 2, 1, 0)
  
  lcm_data$rural_northeast <- ifelse(lcm_data$in_rural + lcm_data$region_northeast == 2, 1, 0)
  lcm_data$rural_midwest <- ifelse(lcm_data$in_rural + lcm_data$region_midwest == 2, 1, 0)
  lcm_data$rural_south <- ifelse(lcm_data$in_rural + lcm_data$region_south == 2, 1, 0)
  lcm_data$rural_wes <- ifelse(lcm_data$in_rural + lcm_data$region_wes == 2, 1, 0)
  
  lcm_data$pop_more_1_mil <- lcm_data$pop_1_mil_to_5_mil +lcm_data$pop_more_5_mil
  lcm_data$pop_100k_to_1_mil <- lcm_data$pop_100k_to_500k +lcm_data$pop_500k_to_1_mil
  lcm_data$pop_less_1_mil <- lcm_data$pop_less_100k + lcm_data$pop_100k_to_1_mil
  
  lcm_data$pop_more_1_mil_northeast <- ifelse(lcm_data$pop_more_1_mil + lcm_data$region_northeast == 2, 1, 0)
  
  lcm_data$cu_size_more_2 <- lcm_data$cu_size_3 + lcm_data$cu_size_4 + 
    lcm_data$cu_size_5 + lcm_data$cu_size_6 + lcm_data$cu_size_7+ lcm_data$cu_size_more_7
  
  lcm_data$cu_size_more_3 <- lcm_data$cu_size_4 + 
    lcm_data$cu_size_5 + lcm_data$cu_size_6 + lcm_data$cu_size_7+ lcm_data$cu_size_more_7
  
  lcm_data$cu_size_more_4 <- lcm_data$cu_size_5 + lcm_data$cu_size_6 + lcm_data$cu_size_7+ lcm_data$cu_size_more_7
  
  lcm_data$mandatory1 <- ifelse(lcm_data$Man_cat == "Zero", 1, 0)
  lcm_data$mandatory2 <- ifelse(lcm_data$Man_cat == "two", 1, 0)
  lcm_data$mandatory3 <- ifelse(lcm_data$Man_cat == "five", 1, 0)
  lcm_data$mandatory4 <- ifelse(lcm_data$Man_cat == "over", 1, 0)
  
  lcm_data$house1 <- ifelse(lcm_data$House_cat == "Zero", 1, 0)
  lcm_data$house2 <- ifelse(lcm_data$House_cat == "two", 1, 0)
  lcm_data$house3 <- ifelse(lcm_data$House_cat == "five", 1, 0)
  lcm_data$house4 <- ifelse(lcm_data$House_cat == "over", 1, 0)
  
  lcm_data$food1 <- ifelse(lcm_data$Food_cat == "OneHudB", 1, 0)
  lcm_data$food2 <- ifelse(lcm_data$Food_cat == "FiveHundredB", 1, 0)
  lcm_data$food3 <- ifelse(lcm_data$Food_cat == "HighFiveHunB", 1, 0)
  
  lcm_data$leisure1 <- ifelse(lcm_data$Lei_cat == "Zero", 1, 0)
  lcm_data$leisure2 <- ifelse(lcm_data$Lei_cat == "HundredB", 1, 0)
  lcm_data$leisure3 <- ifelse(lcm_data$Lei_cat == "HighHunB", 1, 0)
  
  lcm_data$carFuel1 <- ifelse(lcm_data$carFuelP_cat == "Zero", 1, 0)
  lcm_data$carFuel2 <- ifelse(lcm_data$carFuelP_cat == "FiftyB", 1, 0)
  lcm_data$carFuel3 <- ifelse(lcm_data$carFuelP_cat == "HundredB", 1, 0)
  lcm_data$carFuel4 <- ifelse(lcm_data$carFuelP_cat == "HighHunB", 1, 0)
  
  lcm_data$carMain1 <- ifelse(lcm_data$carMainP_cat == "Zero", 1, 0)
  lcm_data$carMain2 <- ifelse(lcm_data$carMainP_cat == "HundredB", 1, 0)
  lcm_data$carMain3 <- ifelse(lcm_data$carMainP_cat == "HighHunB", 1, 0)
  
  lcm_data$taxi1 <- ifelse(lcm_data$taxiP_cat == "Zero", 1, 0)
  lcm_data$taxi2 <- ifelse(lcm_data$taxiP_cat == "TwentyB", 1, 0)
  lcm_data$taxi3 <- ifelse(lcm_data$taxiP_cat == "TwentyFifty", 1, 0)
  lcm_data$taxi4 <- ifelse(lcm_data$taxiP_cat == "HighFifB", 1, 0)
  
  lcm_data$bus1 <- ifelse(lcm_data$busP_cat == "Zero", 1, 0)
  lcm_data$bus2 <- ifelse(lcm_data$busP_cat == "Any", 1, 0)
  
  lcm_data$train1 <- ifelse(lcm_data$trainP_cat == "Zero", 1, 0)
  lcm_data$train2 <- ifelse(lcm_data$trainP_cat == "TwentyB", 1, 0)
  lcm_data$train3 <- ifelse(lcm_data$trainP_cat == "HighTwB", 1, 0)
  
  lcm_data$air1 <- ifelse(lcm_data$airP_cat == "Zero", 1, 0)
  lcm_data$air2 <- ifelse(lcm_data$airP_cat == "FiveHB", 1, 0)
  lcm_data$air3 <- ifelse(lcm_data$airP_cat == "HighFive", 1, 0)
  
  lcm_data$micro1 <- ifelse(lcm_data$microP_cat == "Zero", 1, 0)
  lcm_data$micro2 <- ifelse(lcm_data$microP_cat == "Any", 1, 0)
  
  

  
  return(lcm_data)
}


exp_data_full <- update_data_for_model(exp_data_full)

# the column names we want to use
# the value is the col_name
# the name is the new name you want to be on the summary table
col_names_to_use <- matrix(c("Count" ,"Count" ,"n",
                             "City Type" ,"Rural" ,"city_type_rural",
                      "City Type", "Urban" , "city_type_urban",
                      "Income","Below $50K" , "income_less_50k",
                      "Income", "Between $50K - $75K" , "income_50k_to_75k",
                      "Income", "Between $75K - $100K" , "income_75k_to_100k",
                      "Income", "Between $100K - $200K" , "income_100k_to_200k",
                      "Income", "Above $200K" , "income_more_200k",
                      "Reference Age", "18 - 34" , "age_ref_18_to_34",
                      "Reference Age", "35 - 44" , "age_ref_35_to_44",
                      "Reference Age", "45 - 54" , "age_ref_45_to_54",
                      "Reference Age", "54+" , "age_ref_more_54",
                      "Region", "Northeast" , "region_northeast",
                      "Region", "Midwest" , "region_midwest",
                      "Region", "South" , "region_south",
                      "Region", "West" , "region_wes",
                      "Education", "Masters Degree or higher" , "edu_masters_doctorate",
                      "Education", "Bachelors Degree" , "edu_bachelors",
                      "Education", "Less Than a Bachelors Degree" , "less_bachelors",
                      "Household Structure","Single Without Children" , "single_no_kids",
                      "Household Structure","Single With Children" , "single_kids",
                      "Household Structure","Married Without Children" , "married_no_kids",
                      "Household Structure","Married With Children" , "married_kids",
                      "City Population","Less Than 1 Million" , "pop_less_1_mil",
                      "City Population","1 Million or More" , "pop_more_1_mil",
                      "Mandatory Spending","Zero" , "mandatory1",
                      "Mandatory Spending","$0.01 - $200.00" , "mandatory2",
                      "Mandatory Spending","$200.01 - $500.00" , "mandatory3",
                      "Mandatory Spending","$500.00 +" , "mandatory4",
                      "House-Related Spending","Zero" , "house1",
                      "House-Related Spending","$0.01 - $200.00" , "house2",
                      "House-Related Spending","$200.01 - $500.00" , "house3",
                      "House-Related Spending","$500.01 +" , "house4",
                      "Food Spending","$0.01 - $100.00" , "food1",
                      "Food Spending","$100.01 - $500.00" , "food2",
                      "Food Spending","$500.01 +" , "food3",
                      "Leisure Spending","Zero" , "leisure1",
                      "Leisure Spending","$0.01 - $100.00" , "leisure2",
                      "Leisure Spending","$100.01 +" , "leisure3",
                      "Car Fuel Expense","None" , "carFuel1",
                      "Car Fuel Expense","$0.01 - $50.00" , "carFuel2",
                      "Car Fuel Expense","$50.01 - $100.00" , "carFuel3",
                      "Car Fuel Expense","$100.01 +" , "carFuel4",
                      "Car Maintenance Expense","None" , "carMain1",
                      "Car Maintenance Expense","$0.01 - $100.00" , "carMain2",
                      "Car Maintenance Expense","$100.01 +" , "carMain3",
                      "Ridesharing Expense","None" , "taxi1",
                      "Ridesharing Expense","0.01 - $20.00" , "taxi2",
                      "Ridesharing Expense","20.01 - $50.00" , "taxi3",
                      "Ridesharing Expense","$50.01 +" , "taxi4",
                      "Transit (Bus) Expense","None" , "bus1",
                      "Transit (Bus) Expense","Any" , "bus2",
                      "Transit (Rail) Expense","None" , "train1",
                      "Transit (Rail) Expense","$0.01 - $20.00" , "train2",
                      "Transit (Rail) Expense","$20.01 +" , "train3",
                      "Microtransit Expense","None" , "micro1",
                      "Microtransit Expense","Any" , "micro2",
                      "Air Travel Expense","None" , "air1",
                      "Air Travel Expense","$0.01 - $500.00" , "air2",
                      "Air Travel Expense","$501.00 +" , "air3"
                      ), ncol = 3, byrow = T) |>
  as.data.frame()
  
names(col_names_to_use) <- c("group","nice_name","variable")



```

I ended up taking this data, formatting it in excel, and using it from the excel sheet.

```{r}
#| label: tbl-descriptives-by-hhtype
#| tbl-cap: "Demograhic distribution grouped by differenct household structures"
#| tbl-alt: "A table with the shares of different demographic variables in the data split up by household type"


profiled_data <- exp_data_full |>
  mutate(profile = case_when(
    married_kids == 1 ~ "Married with children",
    married_no_kids == 1 ~ "Married without children",
    single_kids == 1 ~ "Not married but with children",
    single_no_kids == 1 ~ "Not married and no children",
    TRUE ~ "Other"
  )) |>
  select(any_of(col_names_to_use$variable), profile)

new_data <- profiled_data |>
  group_by(profile) |>
  summarise(n = n(),across(any_of(col_names_to_use$variable),  \(x) mean(x, na.rm = TRUE)))

transposed_data <- t(new_data) |> as.data.frame()

names(transposed_data) <- transposed_data[1,] |> as.character()

transposed_data <- transposed_data[2:nrow(transposed_data),]

transposed_data[] <- lapply(transposed_data, as.numeric)

nice_data <- transposed_data |>
  mutate(variable = rownames(transposed_data)) |>
  left_join(col_names_to_use, by = "variable") |>
  mutate("Married with children" = paste0(round(`Married with children` *100,1),"%"),
         "Married without children" = paste0(round(`Married without children` *100,1),"%"),
         "Not married but with children" = paste0(round(`Not married but with children` *100,1),"%"),
         "Not married and no children" = paste0(round(`Not married and no children` *100,1),"%"))

row_vals <- nice_data[nice_data$variable == "n",] |> as.character()
nice_data[nice_data$variable == "n",] <- ifelse(grepl("%",row_vals),
                                                as.character(as.numeric(substr(row_vals, 1, nchar(row_vals)-1)) / 100),
                                                row_vals)

nice_data |>
  select(!variable) |>
  gt(groupname_col = "group",
                rowname_col = "nice_name") |>
  row_group_order(c("Count",
                                          "Reference Age",
                                          "Education",
                                          "Income",
                                          "Household Structure",
                                          "Region"  ,
                                          "City Population" ,
                    "City Type",
                                          "Mandatory Spending" ,
                                          "House-Related Spending"   ,
                                          "Food Spending",
                                          "Leisure Spending",
                                            "Car Fuel Expense",
                                            "Car Maintenance Expense",
                                            "Ridesharing Expense",
                                            "Transit (Bus) Expense",
                                            "Transit (Rail) Expense",
                                            "Microtransit Expense",
                                            "Air Travel Expense"))

```
