---
title: "Category Spending Tables"
editor: visual
html-table-processing: none
---

```{r}
library(tidyverse)
library(readxl)
library(gt)
library(knitr)

ucc <- read_excel("../data/data_prep_input/ucc_categories.xlsx") |>
  filter(in_exp_file == 1)
names(ucc)[1] <- "UCC"

lcm <- read.csv("../data/diary24_combined/created_data/exp_fmly_data.csv")

exp <- read_csv("../data/diary24_combined/expd.csv", guess_max = 10000)

exp <- exp |>
  # separate the NEWID to get CUID and WEEKI
  mutate(CUID = substr(NEWID,2,7),
         WEEKI = substr(NEWID,8,8)) |>
  
  # sum expenses of each ucc code per household
  group_by(CUID, UCC) |>
  summarize(tot_cost = sum(COST)) |>
  ungroup() |>
  
  # get rid of expenses made by households only in the survey for one week
  filter(CUID %in% lcm$CUID)

# join to get the categories
joined_exp <- left_join(exp, ucc, by = "UCC")

# summarize to get average for each category
grouped_exp <- joined_exp |>
  group_by(broad_category) |>
  summarise(tot_spending = sum(tot_cost),
            count = length(unique(CUID))) |>
  mutate(avg_exp_zeros = tot_spending / nrow(lcm),
         avg_exp_no_zeros = tot_spending / count)

# summarize to get average for each transportation category
transpo_exp <- joined_exp |>
  filter(broad_category == "Transportation") |>
  group_by(category) |>
  summarise(tot_spending = sum(tot_cost),
            count = length(unique(CUID))) |>
  mutate(avg_exp_zeros = tot_spending / nrow(lcm),
         avg_exp_no_zeros = tot_spending / count)



```

```{r}
#| label: tbl-transpo-spending
#| tbl-cap: "Average Transportation Spending per Household in Each Category"
#| tbl-alt: "A table of Transportation Average Spending per Household in Each Category"

transpo_exp |> 
  mutate(pct_zeros = avg_exp_zeros * 100 / sum(avg_exp_zeros),
         pct_no_zeros = avg_exp_no_zeros * 100 / sum(avg_exp_no_zeros)) |>
  arrange(desc(count)) |>
  mutate(avg_exp_zeros = paste0("$",round(avg_exp_zeros, 2), " (",round(pct_zeros,2),"%)"),
         avg_exp_no_zeros = paste0("$",round(avg_exp_no_zeros, 2), " (",round(pct_no_zeros,2),"%)"),
         count_pct = paste0(count, " (",round(count * 100 / 6004,1),"% of sample)")) |>
  
  select(`Spending Category` = category, 
         `Average spending including all households` = avg_exp_zeros,
         `Average spending for only households that spent some in this category` = avg_exp_no_zeros,
         `Households with spending in this category` = count_pct) |>
  gt()

```
